[project]
name = "javascript"
version = "0.1.0"
description = "Add a short description here"
authors = ["Rahul Dave <rahuldave@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "osx-64"]

[tasks]

[dependencies]
deno = ">=1.43.6,<1.44"
